# Generated by Django 3.2 on 2021-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_ind', models.CharField(max_length=20)),
                ('name_unique', models.CharField(max_length=20)),
                ('quantity_unique', models.IntegerField()),
                ('unit_unique', models.CharField(max_length=20)),
            ],
        ),
    ]
