# Generated by Django 3.2 on 2021-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerpages', '0002_auto_20210510_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('today_sale', models.IntegerField()),
            ],
        ),
    ]
