# Generated by Django 3.2 on 2021-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subname', models.CharField(max_length=20)),
                ('price_medium', models.IntegerField()),
                ('price_large', models.IntegerField()),
                ('image', models.ImageField(upload_to='menu')),
                ('bgcolor', models.CharField(max_length=20)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
