# Generated by Django 3.2 on 2021-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='offer',
            field=models.BooleanField(default=True),
        ),
    ]
