# Generated by Django 3.2 on 2021-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_drink_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='classname',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
