# Generated by Django 3.2 on 2021-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_cart_item_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_ind',
            field=models.CharField(max_length=7),
        ),
    ]
