# Generated by Django 3.2 on 2021-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_cart_item_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_check',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
