# Generated by Django 3.2 on 2021-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_cart_item_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('flavor', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=15)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
